### ISSUE TITLE
bug report (damage will persist after round end, into the next round), + ideas to add?

### ISSUE THREAD

**Issue by KrappyKraberMain** [Heisenberg3666/Surface-Tension#1]
there is an odd issue in version 2.1.0. It seems that the damage will persist through to the next rounds, endlessly. At least when there is only one person, and the round is restarted via the RA console. plz fix
also, a very minor issue, the plugin will damage players in god mode.

also, some ideas for things you could add.
more damage options, like separate damage multipliers for humans and scp's, separate damage settings for scp's and humans, etc (ex; scp's have a 10 second delay for damage, humans a 100 second delay), etc.
damage stages/intensities, so you can make damage ramp up over time, etc. separate stages for scp's and humans?
maybe the plugin's damage can multiply x amount, over y amount of time? a continuous increase in damage, or have it jump up in damage in segmented increments?
more announcements? one a configurable delay after nuke detonation (saying how much time until you will start to take damage), then one at the same time you start to take damage. different announcements for different stages/intensity levels?

here is a super scuffed pseudo config to (hopefully) better demonstrate my idea. idk how to make a config that would actually function, lol. hopefully the link works.
[scuffed config.txt](https://github.com/Heisenberg3666/Surface-Tension/files/8558844/scuffed.config.txt)

**Comment by KrappyKraberMain** [comment]
also the config folder for the plugin is misspelt

**Comment by Heisenberg3666** [comment]
Should be fixed in the new update: https://github.com/Heisenberg3666/Surface-Tension/releases/tag/v2.2.0
